@host = http://localhost:3000

###
get {{host}}/data/seguidores/1

###
get {{host}}/data/produtoByUsuario?id_usuario=5&modo=incluir

###
get {{host}}/data/usuario
Content-Type: application/json

{

}       

###
post {{host}}
Content-Type: application/json



###
post {{host}}/data/segue
Content-Type: application/json

{
       
}    