@host = http://localhost:3000
@token = 

###
get {{host}}/api/usuario/3f988b44-a034-45e0-9e6b-07b949b28b74
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZjk4OGI0NC1hMDM0LTQ1ZTAtOWU2Yi0wN2I5NDliMjhiNzQiLCJpYXQiOjE3NjQ0NjQ3ODQsImV4cCI6MTc2NDQ2ODM4NH0.QKVtGhZzl0v1-JmGz74U3suKpc-Lcf0lx-6cLlcQfv8

###
get {{host}}/api/usuario/3f988b44-a034-45e0-9e6b-07b949b28b74/avaliadores
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZjk4OGI0NC1hMDM0LTQ1ZTAtOWU2Yi0wN2I5NDliMjhiNzQiLCJpYXQiOjE3NjQ0NjQ3ODQsImV4cCI6MTc2NDQ2ODM4NH0.QKVtGhZzl0v1-JmGz74U3suKpc-Lcf0lx-6cLlcQfv8

###
post {{host}}/api/signin
Content-Type: application/json

{
    "email": "emanuel.eduardo@academico.ifpb.edu.br",
    "senha": "krobus123"
}

###
post {{host}}/api/usuario/3/denuncia
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzU3NDc1MDgzLCJleHAiOjE3NTc0Nzg2ODN9.XOLeJU6TJn-XKTSWLN_WRAvRLx6cm6IjqNnE-0CXZzc

{
    "denunciado": "3",
    "descricao": "Usuário muito bom, recomendo!"
}

###
delete {{host}}/api/usuario/2/seguir
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzU3NDc1MDgzLCJleHAiOjE3NTc0Nzg2ODN9.XOLeJU6TJn-XKTSWLN_WRAvRLx6cm6IjqNnE-0CXZzc

{
    "seguido": "3"
}

###
post {{host}}
Content-Type: application/json



###
post {{host}}/data/segue
Content-Type: application/json

{
       
}    