@host = http://localhost:3000

get {{host}}/data/segue

###
get {{host}}/produto.html

###
post {{host}}/data/livro
Content-Type: application/json

{
        "id_prod": 2,
        "id_usuario": 2,
        "nome": "2a",
        "valor": "preco", 
        "condicao": "estado",
        "descricao": "descricao",
        "autor": "autor",
        "edicao": "gravadora",
        "qtd_pag":" null"
}

###
GET {{host}}/data/livro?id_prod=44f2527e-9955-48d9-8066-77f968530019