@host = http://localhost:3000

get {{host}}/data/segue

###
get {{host}}/produto.html

###
delete {{host}}/data/segue
Content-Type: application/json

{
  "seguido": 2, "seguinte": 3
}

###
GET {{host}}/data/palavra_chave